# Generated by Django 3.2.6 on 2021-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extenciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numextension',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
