# Generated by Django 3.2.6 on 2021-08-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extenciones', '0002_alter_numextension_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numextension',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
