# Generated by Django 3.2.6 on 2021-08-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extenciones', '0005_auto_20210823_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dirextencion',
            options={'verbose_name': 'DirExtencione', 'verbose_name_plural': 'DirExtenciones'},
        ),
        migrations.AlterField(
            model_name='dirextencion',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dirextencion',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
