# Generated by Django 3.2.6 on 2021-08-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extenciones', '0006_auto_20210824_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numextension',
            old_name='numero',
            new_name='extension',
        ),
        migrations.AlterField(
            model_name='dirextencion',
            name='cedula',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='dirextencion',
            name='pin',
            field=models.IntegerField(default=True),
        ),
    ]
