# Generated by Django 3.2.6 on 2021-08-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extenciones', '0007_auto_20210824_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirextencion',
            name='extension',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extenciones.numextension'),
        ),
    ]
