# Generated by Django 3.2.6 on 2021-08-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extenciones', '0008_alter_dirextencion_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirextencion',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
