# Generated by Django 3.2.6 on 2021-08-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extenciones', '0010_alter_dirextencion_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirextencion',
            name='grado',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='numextension',
            name='extension',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
