# Generated by Django 3.2.6 on 2021-08-16 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='directoriomebuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cai', models.CharField(max_length=60)),
                ('cuadrante', models.CharField(max_length=40)),
                ('patrulla', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependencias.dependencia')),
            ],
        ),
    ]
