# Generated by Django 3.2.6 on 2021-08-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebuc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoriomebuc',
            options={'verbose_name': 'Directoriomebuc', 'verbose_name_plural': 'Directoriomebucs'},
        ),
    ]
