# Generated by Django 3.2.6 on 2021-08-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebuc', '0002_alter_directoriomebuc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoriomebuc',
            options={},
        ),
        migrations.RenameField(
            model_name='directoriomebuc',
            old_name='nombre',
            new_name='dependencia',
        ),
    ]
