# Generated by Django 3.2.6 on 2021-08-19 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mebuc', '0003_auto_20210816_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoriomebuc',
            options={'verbose_name': 'Metropolitana', 'verbose_name_plural': 'Metropolitanas'},
        ),
        migrations.AddField(
            model_name='directoriomebuc',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directoriomebuc',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion'),
        ),
    ]
