# Generated by Django 3.2.6 on 2021-08-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebuc', '0004_auto_20210818_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoriomebuc',
            options={'verbose_name': 'Mebuc', 'verbose_name_plural': 'Mebuc'},
        ),
    ]
