# Generated by Django 3.2.6 on 2021-08-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_servicio_clasesserviciomodel_servicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasesserviciomodel',
            options={'verbose_name': 'servicios', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AlterModelOptions(
            name='serviciosmodel',
            options={'verbose_name': 'ServicioModel', 'verbose_name_plural': 'ServiciosModels'},
        ),
        migrations.AlterField(
            model_name='serviciosmodel',
            name='fecha',
            field=models.DateField(verbose_name='Dia servicio'),
        ),
        migrations.AlterField(
            model_name='serviciosmodel',
            name='fechaNotificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
