# Generated by Django 3.2.6 on 2021-08-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencia',
            old_name='nombre',
            new_name='dependencia',
        ),
    ]
