# Generated by Django 3.2.6 on 2021-08-19 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0003_alter_dependencia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencia',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion'),
        ),
    ]
