# Generated by Django 3.2.6 on 2021-08-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencias', '0004_auto_20210818_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='direccion',
            field=models.CharField(max_length=80),
        ),
    ]
